export const en = {
  // ── App-wide ──
  appTitle: 'Study Design & Sample Size Helper',
  appSubtitle: 'A simple, bilingual guide for clinicians planning studies and theses.',
  langToggle: 'Türkçe',
  privacyNote: 'Enter summary values only. Do not enter patient-level or identifying data.',
  footerText: '© 2025 Study Design & Sample Size Helper. For educational and planning purposes only.',
  footerAbout: 'About & Limitations',
  footerPrivacy: 'Privacy',
  backHome: 'Back to Home',
  backToCalc: 'Back',
  reset: 'Reset',
  calculate: 'Calculate',
  copyLink: 'Copy Link',
  copied: 'Copied!',
  shareLink: 'Share This Calculation',
  shareLinkDesc: 'Copy this link to share your calculation with colleagues. No patient data is included.',
  learnMore: 'Learn more',
  close: 'Close',
  details: 'Details',
  showAdvanced: 'Advanced Options',
  hideAdvanced: 'Hide Advanced Options',

  // ── Homepage cards ──
  home: {
    hero: 'Study Design & Sample Size Helper',
    heroSub: 'A simple, bilingual guide for clinicians planning studies and theses.',
    card1Title: 'Help me choose',
    card1Desc: 'Not sure where to start? We\'ll guide you with examples.',
    card2Title: 'Estimate how common something is',
    card2Desc: 'e.g. "What proportion of diabetic patients have retinopathy?"',
    card3Title: 'Compare two groups',
    card3Desc: 'e.g. "Does the new treatment lower blood pressure more?"',
    card4Title: 'Find predictors of an outcome',
    card4Desc: 'e.g. "Which factors predict mortality in ICU patients?"',
    card5Title: 'I already have data',
    card5Desc: 'You already started collecting — let\'s see what\'s still possible.',
    sharedLink: 'Open a shared link or continue',
  },

  // ── Wizard ──
  wizard: {
    title: 'Let\'s find the right path',
    subtitle: 'Which of these best describes your study?',
    opt1: 'I want to estimate how common something is in one group',
    opt1Ex: 'e.g. prevalence of hypertension in a clinic population',
    opt2: 'I want to compare two groups',
    opt2Ex: 'e.g. treatment vs control, exposed vs unexposed',
    opt3: 'I want to examine predictors of an outcome',
    opt3Ex: 'e.g. which factors predict readmission or mortality',
    opt4: 'I already collected some data and want to know what is still possible',
    opt4Ex: 'e.g. I have 80 patients — is that enough?',
    opt5: 'I\'m not sure — guide me with examples',
    opt5Ex: 'We\'ll walk through clinical scenarios together',

    // Compare sub-question
    compareTitle: 'What kind of result are you comparing?',
    compareNum: 'A number',
    compareNumEx: 'e.g. blood pressure, HbA1c, hospital stay',
    compareNumLabel: 'continuous outcome',
    compareBin: 'A yes/no outcome',
    compareBinEx: 'e.g. mortality, remission, complication',
    compareBinLabel: 'binary outcome',

    // "Not sure" examples
    notSureTitle: 'Let\'s start from a clinical question',
    notSureEx1: '"What percentage of my patients have condition X?"',
    notSureEx1Route: 'This sounds like a prevalence study →',
    notSureEx2: '"Does treatment A work better than treatment B?"',
    notSureEx2Route: 'This sounds like a two-group comparison →',
    notSureEx3: '"Which patient factors predict outcome Y?"',
    notSureEx3Route: 'This sounds like a predictor study →',
    notSureEx4: '"I already have 120 patients in my dataset."',
    notSureEx4Route: 'Let\'s work with what you have →',
  },

  // ── Prevalence calculator ──
  prevalence: {
    title: 'Prevalence / One-Proportion Sample Size',
    subtitle: 'Estimate the sample size needed to measure how common something is.',
    prevalenceLabel: 'Expected prevalence',
    prevalenceHelp: 'Your best estimate of the proportion with the condition.',
    prevalenceUnknown: 'If you\'re unsure, 50% is the most conservative (largest sample) default.',
    marginLabel: 'Desired margin of error',
    marginHelp: 'How close you want your estimate to be. For example, ±5% means your true value is likely within 5 percentage points of your estimate.',
    confidenceLabel: 'Confidence level',
    nonresponseLabel: 'Expected nonresponse / attrition',
    nonresponseHelp: 'Percentage of participants you expect to lose.',
    resultTitle: 'Suggested Target Sample Size',
    resultN0: 'Before adjustment',
    resultNAdj: 'After adjusting for nonresponse',
    resultExplain: 'Based on the assumptions you entered, you would need approximately {n} participants to estimate the prevalence with a margin of error of ±{margin}%.',
    plotTitle: 'Precision vs Sample Size',
    plotXLabel: 'Sample Size',
    plotYLabel: 'Margin of Error (±%)',
  },

  // ── Two Proportions ──
  twoProportions: {
    title: 'Two-Group Comparison: Proportions',
    subtitle: 'Estimate sample size to compare a yes/no outcome between two groups.',
    inputMode: 'How would you like to enter values?',
    inputModeDirect: 'Enter both group proportions',
    inputModeDiff: 'Enter baseline + difference',
    p1Label: 'Expected proportion in Group 1',
    p1Help: 'e.g. event rate in the control or unexposed group.',
    p2Label: 'Expected proportion in Group 2',
    p2Help: 'e.g. event rate in the treatment or exposed group.',
    baselineLabel: 'Baseline proportion',
    diffLabel: 'Smallest absolute difference worth detecting',
    diffHelp: 'Use the smallest difference that would matter clinically.',
    alphaLabel: 'Significance level (α)',
    powerLabel: 'Power (1 − β)',
    attritionLabel: 'Expected attrition / nonresponse',
    resultTitle: 'Suggested Target Sample Size',
    resultPerGroup: 'Per group',
    resultTotal: 'Total',
    resultPerGroupAdj: 'Per group (adjusted)',
    resultTotalAdj: 'Total (adjusted)',
    resultExplain: 'Based on the assumptions you entered, you would need approximately {n} participants per group ({total} total) to detect an absolute difference of {diff} percentage points.',
    plotTitle: 'Required Sample Size vs Absolute Difference',
    plotXLabel: 'Absolute Difference (%)',
    plotYLabel: 'Total Sample Size',
    effectHelper: 'Quick reference for absolute differences:',
    effectSmall: '5% — small difference',
    effectMedium: '10% — moderate difference',
    effectLarge: '15% — large difference',
    effectNote: 'Use the smallest difference that would matter clinically.',
  },

  // ── Two Means ──
  twoMeans: {
    title: 'Two-Group Comparison: Means',
    subtitle: 'Estimate sample size to compare a numeric outcome between two groups.',
    deltaLabel: 'Smallest mean difference worth detecting',
    deltaHelp: 'The smallest difference between group means that would be clinically meaningful.',
    sigmaLabel: 'Expected standard deviation (SD)',
    sigmaHelp: 'A common SD for both groups. If unsure, look for SDs in published studies.',
    sdMode: 'SD input method',
    sdModeCommon: 'One common SD',
    sdModeSeparate: 'Separate SDs for each group',
    sd1Label: 'SD for Group 1',
    sd2Label: 'SD for Group 2',
    pooledSD: 'Pooled planning SD',
    alphaLabel: 'Significance level (α)',
    powerLabel: 'Power (1 − β)',
    attritionLabel: 'Expected attrition / nonresponse',
    resultTitle: 'Suggested Target Sample Size',
    resultPerGroup: 'Per group',
    resultTotal: 'Total',
    resultPerGroupAdj: 'Per group (adjusted)',
    resultTotalAdj: 'Total (adjusted)',
    resultExplain: 'Based on the assumptions you entered, you would need approximately {n} participants per group ({total} total) to detect a mean difference of {delta} (SD = {sigma}).',
    plotTitle: 'Required Sample Size vs Mean Difference',
    plotXLabel: 'Mean Difference',
    plotYLabel: 'Total Sample Size',
    cohenHelper: 'Quick reference (Cohen\'s d):',
    cohenSmall: 'd = 0.2 — small effect',
    cohenMedium: 'd = 0.5 — medium effect',
    cohenLarge: 'd = 0.8 — large effect',
    cohenNote: 'These are generic shortcuts and may not reflect clinical importance.',
    cohenApply: 'Apply: difference = d × SD',
  },

  // ── Predictors ──
  predictors: {
    title: 'Predictors of an Outcome',
    subtitle: 'Rough planning guidance for predictor studies.',
    betaNote: 'This is a simplified planning aid for predictor studies. Use it as a rough guide, not a final statistical consultation.',
    outcomeType: 'What type is your outcome?',
    outcomeBinary: 'Binary (yes/no)',
    outcomeBinaryEx: 'e.g. mortality, readmission, complication',
    outcomeContinuous: 'Continuous (a number)',
    outcomeContinuousEx: 'e.g. length of stay, blood pressure, cost',
    eventRateLabel: 'Anticipated event rate',
    eventRateHelp: 'What proportion of your sample do you expect to have the outcome event?',
    predictorsLabel: 'Number of candidate predictors',
    predictorsHelp: 'How many variables you plan to test in your model.',
    epvLabel: 'Events per variable (EPV)',
    epvHelp: 'A common rule of thumb. 10–20 is typical; 15 is a reasonable default.',
    resultTitle: 'Rough Sample Size Range',
    resultEventsNeeded: 'Events needed',
    resultLow: 'Minimum (EPV = 10)',
    resultPreferred: 'Preferred (EPV = 15)',
    resultHigh: 'Conservative (EPV = 20)',
    resultExplain: 'With an event rate of {rate}% and {k} candidate predictors, you would need approximately {events} outcome events. This corresponds to a total sample of roughly {n} participants.',
    resultContinuousTitle: 'Rough Minimum Sample Size',
    resultModelRule: 'Overall model rule (50 + 8k)',
    resultPredRule: 'Individual predictor rule (104 + k)',
    resultRecommended: 'Recommended minimum',
    resultContinuousExplain: 'With {k} candidate predictors, a rough minimum sample size of {n} is suggested.',
    approxWarning: 'These estimates are approximate planning aids. Consult a statistician for complex predictor models.',
  },

  // ── Already Have Data ──
  alreadyHaveData: {
    title: 'I Already Have Data',
    subtitle: 'Sample size planning usually comes first, but you still have options.',
    leadText: 'We can work with what you already know. Choose what fits your situation best.',
    opt1: 'What precision does my current sample give me?',
    opt1Ex: 'For prevalence / proportion studies',
    opt2: 'What difference can I detect with my current sample?',
    opt2Ex: 'For two-group comparison studies',
    opt3: 'How many more do I need?',
    opt3Ex: 'Calculate additional participants needed',

    // AHD Prevalence
    precisionTitle: 'Precision With Your Current Sample',
    currentNLabel: 'Current sample size',
    prevalenceLabel: 'Observed or expected prevalence',
    confidenceLabel: 'Confidence level',
    precisionResult: 'Current Precision',
    precisionMargin: 'Margin of error (±)',
    precisionExplain: 'With {n} participants and an estimated prevalence of {p}%, your confidence interval half-width is approximately ±{hw}%.',
    precisionPlotTitle: 'Margin of Error vs Sample Size',

    // AHD Two groups
    detectTitle: 'Detectable Difference With Your Current Sample',
    detectType: 'What type of comparison?',
    detectMeans: 'Comparing means (a number)',
    detectProportions: 'Comparing proportions (yes/no)',
    currentNPerGroupLabel: 'Current sample size per group',
    sigmaLabel: 'Expected SD',
    baselineLabel: 'Baseline event proportion',
    alphaLabel: 'Significance level (α)',
    powerLabel: 'Power (1 − β)',
    detectMeansResult: 'Smallest Detectable Mean Difference',
    detectMeansExplain: 'With {n} participants per group (SD = {sigma}), the smallest mean difference you can reliably detect is approximately {delta}.',
    detectPropResult: 'Smallest Detectable Absolute Difference',
    detectPropExplain: 'With {n} participants per group and a baseline proportion of {p}%, the smallest absolute difference you can reliably detect is approximately {diff}%.',

    // Additional needed
    additionalTitle: 'Additional Participants Needed',
    targetNLabel: 'Target sample size (from a calculator above)',
    currentNTotalLabel: 'Current total sample size',
    additionalResult: 'Additional Needed',
    additionalExplain: 'You would need approximately {n} more participants to reach your target.',
    additionalNone: 'Your current sample already meets or exceeds the target. You may not need additional participants.',

    // Post-hoc power warning
    postHocTitle: 'A note about post-hoc power',
    postHocWarning: 'Usually it is more helpful to think about precision, detectable difference, or additional sample needed. Post-hoc power calculated from observed effects in a completed study can be misleading.',
  },

  // ── Methods paragraph ──
  methods: {
    title: 'Methods Paragraph',
    subtitle: 'Copy-ready text for your methods section.',
    copyText: 'Copy Text',
    prevalence: 'Sample size was estimated for a single-group prevalence study. Assuming a prevalence of {p}%, with a desired margin of error of ±{d}% and {cl}% confidence, the required sample size was {n0} participants. After allowing for {nr}% nonresponse, the target sample size was increased to {n}.',
    twoProportions: 'Sample size was estimated for a two-group comparison of proportions. Assuming an outcome proportion of {p1}% in group 1 and {p2}% in group 2, with a two-sided alpha of {alpha} and {power}% power, the required sample size was {n} participants per group ({total} total). After allowing for {att}% attrition/nonresponse, the target sample size was increased to {nAdj} per group ({totalAdj} total).',
    twoMeans: 'Sample size was estimated for a two-group comparison of means. Assuming a minimum detectable mean difference of {delta} with a common standard deviation of {sigma}, a two-sided alpha of {alpha}, and {power}% power, the required sample size was {n} participants per group ({total} total). After allowing for {att}% attrition/nonresponse, the target sample size was increased to {nAdj} per group ({totalAdj} total).',
  },

  // ── Checklist ──
  checklist: {
    title: 'Reporting Checklist',
    mainOutcome: 'Main outcome stated',
    assumptions: 'Assumptions stated',
    alphaPower: 'Alpha and power stated',
    attrition: 'Attrition allowance stated',
    finalTarget: 'Final target sample size stated',
  },

  // ── Assumptions ──
  assumptions: {
    title: 'Assumptions Summary',
  },

  // ── Literature helper ──
  literature: {
    title: 'How do I find these numbers?',
    prevalence: {
      intro: 'Look for previous studies reporting:',
      item1: 'Prevalence of the condition in a similar population',
      item2: 'Similar setting, country, or specialty if possible',
      searches: 'Example search phrases:',
      search1: '"[condition] prevalence [population]"',
      search2: '"[condition] prevalence [country]"',
      search3: '"[condition] cross-sectional prevalence study"',
      fallback: 'If no literature is available, 50% is the most conservative starting point (it produces the largest required sample size).',
    },
    twoProportions: {
      intro: 'Look for previous studies reporting:',
      item1: 'Event rates in each group (control vs intervention, or exposed vs unexposed)',
      item2: 'Proportions, risks, or percentages for the outcome',
      searches: 'Example search phrases:',
      search1: '"[outcome] [group A] [group B] proportion"',
      search2: '"[outcome] risk in [population] treatment control"',
      search3: '"[outcome] cohort trial percentage"',
      fallback: 'If literature is limited, start with a clinically meaningful difference and work from there.',
    },
    twoMeans: {
      intro: 'Look for previous studies reporting:',
      item1: 'Means and SDs of the outcome in relevant groups',
      item2: 'Smallest clinically meaningful difference, if known',
      searches: 'Example search phrases:',
      search1: '"[outcome] mean standard deviation [population]"',
      search2: '"[outcome] SD [disease]"',
      search3: '"[outcome] minimal clinically important difference"',
      fallback: 'When literature values are weak, you can use sensitivity analysis: try a range of plausible SDs.',
    },
    predictors: {
      intro: 'Look for previous studies reporting:',
      item1: 'Outcome event rate in similar populations',
      item2: 'Number of candidate predictors typically tested',
      item3: 'Prior multivariable models in similar populations',
      fallback: 'Start with your planned list of predictors and a reasonable event-rate estimate.',
    },
  },

  // ── About page ──
  about: {
    title: 'About & Limitations',
    what: 'What this app does',
    whatText: 'This app helps clinicians and trainees estimate sample sizes for common study designs. It focuses on simplicity and plain language rather than comprehensive statistical coverage.',
    who: 'Who it\'s for',
    whoText: 'Internal medicine fellows, public health trainees, clinicians doing theses, and physicians with limited formal statistics training.',
    doesNot: 'What it does NOT do',
    doesNotItems: [
      'It does not replace statistical consultation for complex designs.',
      'It does not handle cluster / multilevel / design-effect calculations.',
      'It does not support survival analysis, non-inferiority, or equivalence designs.',
      'It does not perform Bayesian sample size calculations.',
      'It does not store any patient data.',
    ],
    predictorDisclaimer: 'Predictor studies disclaimer',
    predictorDisclaimerText: 'The predictor study path provides rough planning guidance based on simplified rules of thumb. It should not be treated as a definitive sample size calculation.',
    references: 'References',
    referencesItems: [
      'Fleiss JL, Levin B, Paik MC. Statistical Methods for Rates and Proportions. 3rd ed. Wiley; 2003.',
      'Chow SC, Shao J, Wang H, Lokhnygina Y. Sample Size Calculations in Clinical Research. 3rd ed. Chapman & Hall/CRC; 2018.',
      'Peduzzi P, Concato J, Kemper E, et al. A simulation study of the number of events per variable in logistic regression analysis. J Clin Epidemiol. 1996;49(12):1373-1379.',
      'Green SB. How many subjects does it take to do a regression analysis? Multivariate Behav Res. 1991;26(3):499-510.',
      'Abramowitz M, Stegun IA. Handbook of Mathematical Functions. Dover Publications; 1965.',
    ],
    shareLinksTitle: 'How share links work',
    shareLinksText: 'Share links encode only the calculator type and your entered assumptions (e.g. proportions, alpha, power). They contain no patient or personal information.',
  },

  // ── Privacy page ──
  privacy: {
    title: 'Privacy',
    p1: 'This app does not collect, store, or transmit any personal or patient data.',
    p2: 'All calculations happen entirely in your browser. Nothing is sent to a server.',
    p3: 'Shared links encode only calculator assumptions (proportions, means, statistical parameters). They never contain patient-level or identifying information.',
    p4: 'No cookies are used. The only local storage used is your language preference.',
    p5: 'No analytics or tracking tools are included.',
  },

  // ── Unsupported path ──
  unsupported: {
    title: 'Not fully supported yet',
    text: 'This path is not fully supported yet. Let\'s keep this simple and choose the closest safe starting point.',
    back: 'Go back to choose a different path',
  },
};
