import { en } from './en';

export const tr: typeof en = {
  // ── Uygulama geneli ──
  appTitle: 'Çalışma Tasarımı ve Örneklem Büyüklüğü Yardımcısı',
  appSubtitle: 'Çalışma ve tez planlayan klinisyenler için sade, iki dilli bir rehber.',
  langToggle: 'English',
  privacyNote: 'Yalnızca özet değerler girin. Hasta düzeyinde veya kişisel tanımlayıcı veriler girmeyin.',
  footerText: '© 2025 Çalışma Tasarımı ve Örneklem Büyüklüğü Yardımcısı. Yalnızca eğitim ve planlama amaçlıdır.',
  footerAbout: 'Hakkında ve Sınırlılıklar',
  footerPrivacy: 'Gizlilik',
  backHome: 'Ana Sayfaya Dön',
  backToCalc: 'Geri',
  reset: 'Sıfırla',
  calculate: 'Hesapla',
  copyLink: 'Bağlantıyı Kopyala',
  copied: 'Kopyalandı!',
  shareLink: 'Bu Hesaplamayı Paylaş',
  shareLinkDesc: 'Bu bağlantıyı meslektaşlarınızla paylaşabilirsiniz. Hasta verisi içermez.',
  learnMore: 'Daha fazla bilgi',
  close: 'Kapat',
  details: 'Detaylar',
  showAdvanced: 'Gelişmiş Seçenekler',
  hideAdvanced: 'Gelişmiş Seçenekleri Gizle',

  // ── Ana sayfa kartları ──
  home: {
    hero: 'Çalışma Tasarımı ve Örneklem Büyüklüğü Yardımcısı',
    heroSub: 'Çalışma ve tez planlayan klinisyenler için sade, iki dilli bir rehber.',
    card1Title: 'Bana yardım et',
    card1Desc: 'Nereden başlayacağınızdan emin değil misiniz? Örneklerle yönlendirelim.',
    card2Title: 'Bir şeyin ne kadar yaygın olduğunu tahmin et',
    card2Desc: 'Örn. "Diyabetli hastaların yüzde kaçında retinopati var?"',
    card3Title: 'İki grubu karşılaştır',
    card3Desc: 'Örn. "Yeni tedavi kan basıncını daha fazla düşürüyor mu?"',
    card4Title: 'Bir sonucun belirleyicilerini bul',
    card4Desc: 'Örn. "YBÜ hastalarında mortaliteyi hangi faktörler öngörüyor?"',
    card5Title: 'Zaten verim var',
    card5Desc: 'Veri toplamaya başladınız — hâlâ neler yapılabileceğini görelim.',
    sharedLink: 'Paylaşılan bir bağlantıyı aç veya devam et',
  },

  // ── Yönlendirici ──
  wizard: {
    title: 'Doğru yolu bulalım',
    subtitle: 'Hangisi çalışmanızı en iyi tanımlıyor?',
    opt1: 'Bir grupta bir şeyin ne kadar yaygın olduğunu tahmin etmek istiyorum',
    opt1Ex: 'Örn. bir klinik popülasyonda hipertansiyon prevalansı',
    opt2: 'İki grubu karşılaştırmak istiyorum',
    opt2Ex: 'Örn. tedavi ve kontrol, maruz kalan ve kalmayan',
    opt3: 'Bir sonucun belirleyicilerini incelemek istiyorum',
    opt3Ex: 'Örn. tekrar yatış veya mortaliteyi hangi faktörler öngörüyor',
    opt4: 'Zaten veri topladım ve hâlâ neler yapılabileceğini bilmek istiyorum',
    opt4Ex: 'Örn. 80 hastam var — bu yeterli mi?',
    opt5: 'Emin değilim — örneklerle bana rehberlik et',
    opt5Ex: 'Klinik senaryolar üzerinden birlikte ilerleyelim',

    compareTitle: 'Ne tür bir sonucu karşılaştırıyorsunuz?',
    compareNum: 'Bir sayı',
    compareNumEx: 'Örn. kan basıncı, HbA1c, hastanede kalış süresi',
    compareNumLabel: 'sürekli sonuç değişkeni',
    compareBin: 'Evet/hayır sonucu',
    compareBinEx: 'Örn. mortalite, remisyon, komplikasyon',
    compareBinLabel: 'ikili sonuç değişkeni',

    notSureTitle: 'Klinik bir sorudan başlayalım',
    notSureEx1: '"Hastalarımın yüzde kaçında X durumu var?"',
    notSureEx1Route: 'Bu bir prevalans çalışmasına benziyor →',
    notSureEx2: '"A tedavisi B tedavisinden daha iyi mi?"',
    notSureEx2Route: 'Bu iki grup karşılaştırmasına benziyor →',
    notSureEx3: '"Hangi hasta faktörleri Y sonucunu öngörüyor?"',
    notSureEx3Route: 'Bu bir belirleyici çalışmasına benziyor →',
    notSureEx4: '"Veri setimde zaten 120 hastam var."',
    notSureEx4Route: 'Elinizdekiyle çalışalım →',
  },

  // ── Prevalans hesaplayıcı ──
  prevalence: {
    title: 'Prevalans / Tek Oran Örneklem Büyüklüğü',
    subtitle: 'Bir şeyin ne kadar yaygın olduğunu ölçmek için gereken örneklem büyüklüğünü tahmin edin.',
    prevalenceLabel: 'Beklenen prevalans',
    prevalenceHelp: 'Durumun oranına ilişkin en iyi tahmininiz.',
    prevalenceUnknown: 'Emin değilseniz, %50 en muhafazakâr (en büyük örneklem) varsayımdır.',
    marginLabel: 'İstenen hata payı',
    marginHelp: 'Tahmininizin ne kadar yakın olmasını istiyorsunuz. Örneğin ±%5, gerçek değerin tahmininizden en fazla 5 yüzde puanı uzakta olduğu anlamına gelir.',
    confidenceLabel: 'Güven düzeyi',
    nonresponseLabel: 'Beklenen yanıtsızlık / kayıp oranı',
    nonresponseHelp: 'Kaybedeceğinizi beklediğiniz katılımcı yüzdesi.',
    resultTitle: 'Önerilen Hedef Örneklem Büyüklüğü',
    resultN0: 'Düzeltme öncesi',
    resultNAdj: 'Yanıtsızlık düzeltmesi sonrası',
    resultExplain: 'Girdiğiniz varsayımlara göre, prevalansı ±{margin}% hata payıyla tahmin edebilmek için yaklaşık {n} katılımcıya ihtiyacınız vardır.',
    plotTitle: 'Kesinlik ve Örneklem Büyüklüğü',
    plotXLabel: 'Örneklem Büyüklüğü',
    plotYLabel: 'Hata Payı (±%)',
  },

  // ── İki Oran ──
  twoProportions: {
    title: 'İki Grup Karşılaştırması: Oranlar',
    subtitle: 'İki grup arasındaki evet/hayır sonucunu karşılaştırmak için örneklem büyüklüğünü tahmin edin.',
    inputMode: 'Değerleri nasıl girmek istersiniz?',
    inputModeDirect: 'Her iki grup oranını gir',
    inputModeDiff: 'Başlangıç oranı + fark gir',
    p1Label: 'Grup 1\'de beklenen oran',
    p1Help: 'Örn. kontrol veya maruz kalmayan gruptaki olay oranı.',
    p2Label: 'Grup 2\'de beklenen oran',
    p2Help: 'Örn. tedavi veya maruz kalan gruptaki olay oranı.',
    baselineLabel: 'Başlangıç oranı',
    diffLabel: 'Tespit edilmek istenen en küçük mutlak fark',
    diffHelp: 'Klinik olarak anlamlı olacak en küçük farkı kullanın.',
    alphaLabel: 'Anlamlılık düzeyi (α)',
    powerLabel: 'Güç (1 − β)',
    attritionLabel: 'Beklenen kayıp / yanıtsızlık',
    resultTitle: 'Önerilen Hedef Örneklem Büyüklüğü',
    resultPerGroup: 'Grup başına',
    resultTotal: 'Toplam',
    resultPerGroupAdj: 'Grup başına (düzeltilmiş)',
    resultTotalAdj: 'Toplam (düzeltilmiş)',
    resultExplain: 'Girdiğiniz varsayımlara göre, {diff} yüzde puanlık mutlak bir farkı tespit edebilmek için grup başına yaklaşık {n} katılımcıya (toplam {total}) ihtiyacınız vardır.',
    plotTitle: 'Gerekli Örneklem Büyüklüğü ve Mutlak Fark',
    plotXLabel: 'Mutlak Fark (%)',
    plotYLabel: 'Toplam Örneklem Büyüklüğü',
    effectHelper: 'Mutlak fark için hızlı referans:',
    effectSmall: '%5 — küçük fark',
    effectMedium: '%10 — orta fark',
    effectLarge: '%15 — büyük fark',
    effectNote: 'Klinik olarak anlamlı olacak en küçük farkı kullanın.',
  },

  // ── İki Ortalama ──
  twoMeans: {
    title: 'İki Grup Karşılaştırması: Ortalamalar',
    subtitle: 'İki grup arasındaki sayısal bir sonucu karşılaştırmak için örneklem büyüklüğünü tahmin edin.',
    deltaLabel: 'Tespit edilmek istenen en küçük ortalama fark',
    deltaHelp: 'Grup ortalamaları arasındaki klinik olarak anlamlı olacak en küçük fark.',
    sigmaLabel: 'Beklenen standart sapma (SS)',
    sigmaHelp: 'Her iki grup için ortak SS. Emin değilseniz yayınlanmış çalışmalardan SS değerlerine bakın.',
    sdMode: 'SS giriş yöntemi',
    sdModeCommon: 'Tek ortak SS',
    sdModeSeparate: 'Her grup için ayrı SS',
    sd1Label: 'Grup 1 için SS',
    sd2Label: 'Grup 2 için SS',
    pooledSD: 'Havuzlanmış planlama SS\'si',
    alphaLabel: 'Anlamlılık düzeyi (α)',
    powerLabel: 'Güç (1 − β)',
    attritionLabel: 'Beklenen kayıp / yanıtsızlık',
    resultTitle: 'Önerilen Hedef Örneklem Büyüklüğü',
    resultPerGroup: 'Grup başına',
    resultTotal: 'Toplam',
    resultPerGroupAdj: 'Grup başına (düzeltilmiş)',
    resultTotalAdj: 'Toplam (düzeltilmiş)',
    resultExplain: 'Girdiğiniz varsayımlara göre, {delta} ortalama farkı tespit edebilmek için (SS = {sigma}) grup başına yaklaşık {n} katılımcıya (toplam {total}) ihtiyacınız vardır.',
    plotTitle: 'Gerekli Örneklem Büyüklüğü ve Ortalama Fark',
    plotXLabel: 'Ortalama Fark',
    plotYLabel: 'Toplam Örneklem Büyüklüğü',
    cohenHelper: 'Hızlı referans (Cohen\'s d):',
    cohenSmall: 'd = 0,2 — küçük etki',
    cohenMedium: 'd = 0,5 — orta etki',
    cohenLarge: 'd = 0,8 — büyük etki',
    cohenNote: 'Bunlar genel kısayollardır ve klinik önemi yansıtmayabilir.',
    cohenApply: 'Uygula: fark = d × SS',
  },

  // ── Belirleyiciler ──
  predictors: {
    title: 'Bir Sonucun Belirleyicileri',
    subtitle: 'Belirleyici çalışmaları için yaklaşık planlama rehberi.',
    betaNote: 'Bu, belirleyici çalışmaları için basitleştirilmiş bir planlama yardımcısıdır. Kesin bir istatistiksel danışmanlık yerine yaklaşık bir rehber olarak kullanın.',
    outcomeType: 'Sonuç değişkeninizin tipi nedir?',
    outcomeBinary: 'İkili (evet/hayır)',
    outcomeBinaryEx: 'Örn. mortalite, tekrar yatış, komplikasyon',
    outcomeContinuous: 'Sürekli (bir sayı)',
    outcomeContinuousEx: 'Örn. kalış süresi, kan basıncı, maliyet',
    eventRateLabel: 'Beklenen olay oranı',
    eventRateHelp: 'Örnekleminizin ne kadarının sonuç olayını yaşayacağını bekliyorsunuz?',
    predictorsLabel: 'Aday belirleyici sayısı',
    predictorsHelp: 'Modelinizde test etmeyi planladığınız değişken sayısı.',
    epvLabel: 'Değişken başına olay sayısı (EPV)',
    epvHelp: 'Yaygın bir kural. 10–20 arası tipiktir; 15 makul bir varsayımdır.',
    resultTitle: 'Yaklaşık Örneklem Büyüklüğü Aralığı',
    resultEventsNeeded: 'Gereken olay sayısı',
    resultLow: 'Minimum (EPV = 10)',
    resultPreferred: 'Tercih edilen (EPV = 15)',
    resultHigh: 'Muhafazakâr (EPV = 20)',
    resultExplain: '%{rate} olay oranı ve {k} aday belirleyici ile yaklaşık {events} sonuç olayına ihtiyacınız olacaktır. Bu, yaklaşık {n} katılımcılık toplam örnekleme karşılık gelir.',
    resultContinuousTitle: 'Yaklaşık Minimum Örneklem Büyüklüğü',
    resultModelRule: 'Genel model kuralı (50 + 8k)',
    resultPredRule: 'Bireysel belirleyici kuralı (104 + k)',
    resultRecommended: 'Önerilen minimum',
    resultContinuousExplain: '{k} aday belirleyici ile yaklaşık minimum {n} örneklem büyüklüğü önerilmektedir.',
    approxWarning: 'Bu tahminler yaklaşık planlama yardımcılarıdır. Karmaşık belirleyici modelleri için bir istatistikçiye danışın.',
  },

  // ── Zaten Verim Var ──
  alreadyHaveData: {
    title: 'Zaten Verim Var',
    subtitle: 'Örneklem büyüklüğü planlaması genellikle ilk adımdır, ancak hâlâ seçenekleriniz var.',
    leadText: 'Elinizdekiyle çalışabiliriz. Durumunuza en uygun seçeneği belirleyin.',
    opt1: 'Mevcut örneklemim ne kadar kesinlik veriyor?',
    opt1Ex: 'Prevalans / oran çalışmaları için',
    opt2: 'Mevcut örneklemimle hangi farkı tespit edebilirim?',
    opt2Ex: 'İki grup karşılaştırma çalışmaları için',
    opt3: 'Kaç kişiye daha ihtiyacım var?',
    opt3Ex: 'Ek katılımcı sayısını hesaplayın',

    precisionTitle: 'Mevcut Örnekleminizle Kesinlik',
    currentNLabel: 'Mevcut örneklem büyüklüğü',
    prevalenceLabel: 'Gözlenen veya beklenen prevalans',
    confidenceLabel: 'Güven düzeyi',
    precisionResult: 'Mevcut Kesinlik',
    precisionMargin: 'Hata payı (±)',
    precisionExplain: '{n} katılımcı ve tahmini %{p} prevalans ile, güven aralığı yarı genişliğiniz yaklaşık ±%{hw}\'dir.',
    precisionPlotTitle: 'Hata Payı ve Örneklem Büyüklüğü',

    detectTitle: 'Mevcut Örnekleminizle Tespit Edilebilir Fark',
    detectType: 'Karşılaştırma türü nedir?',
    detectMeans: 'Ortalama karşılaştırma (bir sayı)',
    detectProportions: 'Oran karşılaştırma (evet/hayır)',
    currentNPerGroupLabel: 'Grup başına mevcut örneklem büyüklüğü',
    sigmaLabel: 'Beklenen SS',
    baselineLabel: 'Başlangıç olay oranı',
    alphaLabel: 'Anlamlılık düzeyi (α)',
    powerLabel: 'Güç (1 − β)',
    detectMeansResult: 'Tespit Edilebilir En Küçük Ortalama Fark',
    detectMeansExplain: 'Grup başına {n} katılımcı (SS = {sigma}) ile, güvenilir olarak tespit edebileceğiniz en küçük ortalama fark yaklaşık {delta}\'dır.',
    detectPropResult: 'Tespit Edilebilir En Küçük Mutlak Fark',
    detectPropExplain: 'Grup başına {n} katılımcı ve %{p} başlangıç oranı ile, güvenilir olarak tespit edebileceğiniz en küçük mutlak fark yaklaşık %{diff}\'dir.',

    additionalTitle: 'Ek Katılımcı İhtiyacı',
    targetNLabel: 'Hedef örneklem büyüklüğü (yukarıdaki hesaplayıcıdan)',
    currentNTotalLabel: 'Mevcut toplam örneklem büyüklüğü',
    additionalResult: 'Ek İhtiyaç',
    additionalExplain: 'Hedefinize ulaşmak için yaklaşık {n} daha katılımcıya ihtiyacınız vardır.',
    additionalNone: 'Mevcut örnekleminiz hedefi karşılıyor veya aşıyor. Ek katılımcıya ihtiyacınız olmayabilir.',

    postHocTitle: 'Post-hoc güç hakkında bir not',
    postHocWarning: 'Genellikle kesinlik, tespit edilebilir fark veya ek örneklem ihtiyacı düşünmek daha yararlıdır. Tamamlanmış bir çalışmada gözlenen etkilerden hesaplanan post-hoc güç yanıltıcı olabilir.',
  },

  // ── Yöntemler paragrafı ──
  methods: {
    title: 'Yöntemler Paragrafı',
    subtitle: 'Yöntemler bölümünüz için kopyalanmaya hazır metin.',
    copyText: 'Metni Kopyala',
    prevalence: 'Örneklem büyüklüğü tek gruplu bir prevalans çalışması için hesaplandı. Prevalansın %{p} olacağı, istenen hata payının ±%{d} ve güven düzeyinin %{cl} olacağı varsayıldığında, gerekli örneklem büyüklüğü {n0} katılımcı olarak hesaplandı. %{nr} yanıtsızlık payı eklendiğinde hedef örneklem büyüklüğü {n}\'e çıkarıldı.',
    twoProportions: 'Örneklem büyüklüğü iki grubun oranlarının karşılaştırılması için hesaplandı. Birinci grupta sonuç oranının %{p1}, ikinci grupta %{p2} olacağı; iki yönlü {alpha} anlamlılık düzeyi ve %{power} güç kullanılacağı varsayıldığında, grup başına gerekli örneklem büyüklüğü {n} (toplam {total}) olarak hesaplandı. %{att} kayıp/yanıtsızlık payı eklendiğinde hedef örneklem büyüklüğü grup başına {nAdj} (toplam {totalAdj})\'e çıkarıldı.',
    twoMeans: 'Örneklem büyüklüğü iki grubun ortalamalarının karşılaştırılması için hesaplandı. Tespit edilecek minimum ortalama farkın {delta}, ortak standart sapmanın {sigma}, iki yönlü {alpha} anlamlılık düzeyi ve %{power} güç kullanılacağı varsayıldığında, grup başına gerekli örneklem büyüklüğü {n} (toplam {total}) olarak hesaplandı. %{att} kayıp/yanıtsızlık payı eklendiğinde hedef örneklem büyüklüğü grup başına {nAdj} (toplam {totalAdj})\'e çıkarıldı.',
  },

  // ── Kontrol listesi ──
  checklist: {
    title: 'Raporlama Kontrol Listesi',
    mainOutcome: 'Ana sonuç belirtildi',
    assumptions: 'Varsayımlar belirtildi',
    alphaPower: 'Alfa ve güç belirtildi',
    attrition: 'Kayıp payı belirtildi',
    finalTarget: 'Nihai hedef örneklem büyüklüğü belirtildi',
  },

  // ── Varsayımlar ──
  assumptions: {
    title: 'Varsayımlar Özeti',
  },

  // ── Literatür yardımcısı ──
  literature: {
    title: 'Bu sayıları nasıl bulurum?',
    prevalence: {
      intro: 'Şunu raporlayan önceki çalışmalara bakın:',
      item1: 'Benzer bir popülasyonda durumun prevalansı',
      item2: 'Mümkünse benzer ortam, ülke veya uzmanlık alanı',
      searches: 'Örnek arama cümleleri:',
      search1: '"[durum] prevalans [popülasyon]"',
      search2: '"[durum] prevalans [ülke]"',
      search3: '"[durum] kesitsel prevalans çalışması"',
      fallback: 'Literatür yoksa, %50 en muhafazakâr başlangıç noktasıdır (en büyük gerekli örneklem büyüklüğünü verir).',
    },
    twoProportions: {
      intro: 'Şunu raporlayan önceki çalışmalara bakın:',
      item1: 'Her gruptaki olay oranları (kontrol ve girişim, veya maruz kalan ve kalmayan)',
      item2: 'Sonuç için oranlar, riskler veya yüzdeler',
      searches: 'Örnek arama cümleleri:',
      search1: '"[sonuç] [grup A] [grup B] oran"',
      search2: '"[sonuç] risk [popülasyon] tedavi kontrol"',
      search3: '"[sonuç] kohort çalışma yüzde"',
      fallback: 'Literatür sınırlıysa, klinik olarak anlamlı bir farktan başlayarak ilerleyin.',
    },
    twoMeans: {
      intro: 'Şunu raporlayan önceki çalışmalara bakın:',
      item1: 'İlgili gruplardaki sonucun ortalamaları ve SS\'leri',
      item2: 'Biliniyorsa en küçük klinik olarak anlamlı fark',
      searches: 'Örnek arama cümleleri:',
      search1: '"[sonuç] ortalama standart sapma [popülasyon]"',
      search2: '"[sonuç] SS [hastalık]"',
      search3: '"[sonuç] minimal klinik önemli fark"',
      fallback: 'Literatür değerleri zayıfsa duyarlılık analizi yapabilirsiniz: bir dizi olası SS değeri deneyin.',
    },
    predictors: {
      intro: 'Şunu raporlayan önceki çalışmalara bakın:',
      item1: 'Benzer popülasyonlardaki sonuç olay oranı',
      item2: 'Genellikle test edilen aday belirleyici sayısı',
      item3: 'Benzer popülasyonlardaki önceki çok değişkenli modeller',
      fallback: 'Planlanan belirleyici listeniz ve makul bir olay oranı tahmini ile başlayın.',
    },
  },

  // ── Hakkında sayfası ──
  about: {
    title: 'Hakkında ve Sınırlılıklar',
    what: 'Bu uygulama ne yapar',
    whatText: 'Bu uygulama, klinisyenlerin ve araştırma öğrencilerinin yaygın çalışma tasarımları için örneklem büyüklüğü tahmin etmelerine yardımcı olur. Kapsamlı istatistiksel kapsam yerine sadelik ve anlaşılır dile odaklanır.',
    who: 'Kimin için',
    whoText: 'İç hastalıkları araştırma görevlileri, halk sağlığı öğrencileri, tez yapan klinisyenler ve sınırlı resmi istatistik eğitimine sahip hekimler.',
    doesNot: 'Ne yapmaz',
    doesNotItems: [
      'Karmaşık tasarımlar için istatistiksel danışmanlığın yerini almaz.',
      'Küme / çok düzeyli / tasarım etkisi hesaplamalarını desteklemez.',
      'Sağkalım analizi, non-inferioritite veya eşdeğerlik tasarımlarını desteklemez.',
      'Bayesçi örneklem büyüklüğü hesaplaması yapmaz.',
      'Hiçbir hasta verisi saklamaz.',
    ],
    predictorDisclaimer: 'Belirleyici çalışmaları uyarısı',
    predictorDisclaimerText: 'Belirleyici çalışma yolu, basitleştirilmiş kurallara dayalı yaklaşık planlama rehberliği sağlar. Kesin bir örneklem büyüklüğü hesaplaması olarak değerlendirilmemelidir.',
    references: 'Kaynaklar',
    referencesItems: [
      'Fleiss JL, Levin B, Paik MC. Statistical Methods for Rates and Proportions. 3rd ed. Wiley; 2003.',
      'Chow SC, Shao J, Wang H, Lokhnygina Y. Sample Size Calculations in Clinical Research. 3rd ed. Chapman & Hall/CRC; 2018.',
      'Peduzzi P, Concato J, Kemper E, et al. A simulation study of the number of events per variable in logistic regression analysis. J Clin Epidemiol. 1996;49(12):1373-1379.',
      'Green SB. How many subjects does it take to do a regression analysis? Multivariate Behav Res. 1991;26(3):499-510.',
      'Abramowitz M, Stegun IA. Handbook of Mathematical Functions. Dover Publications; 1965.',
    ],
    shareLinksTitle: 'Paylaşım bağlantıları nasıl çalışır',
    shareLinksText: 'Paylaşım bağlantıları yalnızca hesaplayıcı türü ve girdiğiniz varsayımları (örn. oranlar, alfa, güç) kodlar. Hasta veya kişisel bilgi içermez.',
  },

  // ── Gizlilik sayfası ──
  privacy: {
    title: 'Gizlilik',
    p1: 'Bu uygulama hiçbir kişisel veya hasta verisi toplamaz, saklamaz veya iletmez.',
    p2: 'Tüm hesaplamalar tamamen tarayıcınızda gerçekleşir. Sunucuya hiçbir şey gönderilmez.',
    p3: 'Paylaşılan bağlantılar yalnızca hesaplayıcı varsayımlarını (oranlar, ortalamalar, istatistiksel parametreler) kodlar. Hasta düzeyinde veya tanımlayıcı bilgi içermez.',
    p4: 'Çerez kullanılmaz. Kullanılan tek yerel depolama dil tercihinizdir.',
    p5: 'Analitik veya izleme araçları kullanılmamaktadır.',
  },

  // ── Desteklenmeyen yol ──
  unsupported: {
    title: 'Henüz tam olarak desteklenmiyor',
    text: 'Bu yol henüz tam olarak desteklenmiyor. Basit tutalım ve en yakın güvenli başlangıç noktasını seçelim.',
    back: 'Farklı bir yol seçmek için geri dönün',
  },
};
